### ISSUE TITLE
Input file error

### ISSUE THREAD

**Issue by Arin1643** [Kalan-Lab/lsaBGC-Pan#1]
Traceback (most recent call last):
  File "/home/arin1643/miniconda3/envs/lsaBGC_env/bin/lsaBGC-Pan", line 1039, in <module>
    lsaBGC()
  File "/home/arin1643/miniconda3/envs/lsaBGC_env/bin/lsaBGC-Pan", line 645, in lsaBGC
    with open(genome_gbk) as ogg:
FileNotFoundError: [Errno 2] No such file or directory: '/home/arin1643/lsaBGC-Pan/test_case/lsaBGC-Pan_Results/Gene_Calling/Mangrovibacter_phragmitis.gbk'

I am giving assembly fasta files as input but showing this error. Can you please have a look

**Comment by raufs** [comment]
Hi, 

Thank you for giving lsaBGC-Pan a try and sharing the issue you encountered! 

Can you please share additional details on the input files if you are able to? One thing to note is that lsaBGC-Pan does not do a great job handling genomes with spaces or unexpected characters in their name at the moment, will make it more robust for this in the near future. If this is the case for your input, can you please replace spaces in the names of your input assembly FASTA files if they exist with underscores `_` and see if that resolves the issue.

Kind regards,
Rauf

**Comment by raufs** [comment]
Newest version of lsaBGC-Pan v1.0.6 should now be more robust in accepting input genomes with spaces in their names and also accept providing genomes as a list instead of within a singular directory. Please just let us know if the issues persist.

Rauf

**Comment by raufs** [comment]
I am closing this, but if the issue has not been addressed please feel free to re-open or open a new issue!
